### PR TITLE
UnseenMail

### PR DESCRIPTION
**Pull request by Danaru87**
My script that display unread email count from multiple accounts.
[UnseenMail Official Repo](https://framagit.org/DanaruDev/UnseenMail)

### CODE REVIEW

**Comment by x70b1** [comment]
Why not just use `inbox-imap`?

**Comment by Danaru87** [comment]
The principal reason is "Imap is considered as a less secured protocol by Gmail".

inbox-imap just can be used by only one account at same time.

I'm just requesting a merge because some reddit users want to see my script here ;)

**Comment by x70b1** [comment]
We could add a link [here](https://github.com/x70b1/polybar-scripts#see-also-these-other-user-repositories).
So you can maintain and develop your script in your repo.

**Comment by Danaru87** [comment]
Ok, better solution for me to maintain from my repo.

I cancel the pull request and do another with my repo link in README.

**Pull request closed without merging**
