### PR TITLE
General improvements of the updates-arch scripts

### PR DESCRIPTION
**Pull request by Cybolic**
- Auto-select helper
- Added `yay` helper
- Added fallback for when no known helper is installed

### CODE REVIEW

**Comment by x70b1** [comment]
Nice idea. But is it necessary?
I'm not sure. I guess everyone should know which AUR helper is in use.

**Comment by x70b1** [comment]
But adding `yay` is a good idea.

**Comment by Cybolic** [comment]
The problem I was facing with just adding `yay` as a commented out line (which is what I started with), is that the command for getting the amount of changes for both the repo and aur with `yay` is a one-liner. It bypasses a lot of code in the "combined" version, which I was having trouble making into an easily editable version.

**Comment by x70b1** [comment]
We are a bit at the point where we want make it perfect for everyone. But thats not possible.
I want to make the setup as simple as possible. But that doesn't mean that the scripts fit at all points for your own use case. So we should focus on things that are really helpful. 

I guess its the best idea to add a `yay` example.

You need the `pacman-contrib` package. It contains `checkupdates`. Look at the [module page](https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/updates-arch).

Is there a way to ask `yay` to show only AUR updates?
Then we could add this as example very easy. 

Also we can add a note about the one for all `yay` command.

**Comment by Cybolic** [comment]
I had put it as `yay -Qu --aur --quiet` to match the other helpers, but both should work.

**Comment by x70b1** [comment]
So `yay -Qau` shows all AUR updates only, right?
And `yay -Qu` shows all updates including AUR updates?

Is there a way to show regular updates only?

**Comment by x70b1** [comment]
I opened an issue: [Jguer/yay/issues/715](https://github.com/Jguer/yay/issues/715)

**Comment by Cybolic** [comment]
As suggested, I created a separate script for `yay` in a new pull request.

**Comment by x70b1** [comment]
Ahh. Not so fast :) 
I will wait for the answer at `yay`. If they introduce a solution, we could very easy fix our scripts.

**Comment by Cybolic** [comment]
Fair enough :) I've submitted another pull request that just adds comment to the current scripts for if/when `yay` fix their output. At that point I'll let you decide which version you prefer :)

**Comment by Cybolic** [comment]
What about the commented use of pacman directly to get the repo updates, is that no good?

**Comment by x70b1** [comment]
`pacman -Qu` and `yay -Qu` are the same thing. They return a list of upgrades. The information for that depends on your local package database. 
Means you have to update (with `pacman -Sy` or `yay -Sy` ) the database before you can see the latest updates.

**Pull request closed without merging**
