### PR TITLE
date-calendar: added script

### PR DESCRIPTION
**Pull request by mjturt**

### CODE REVIEW

**Comment by mjturt** [comment]
Yes that's true. I'll make a new pull request.

**Comment by x70b1** [comment]
What is you window manager? I got some problems with `i3wm`. I guess that I should configure floating for `yad`.

**Comment by 132ikl** [comment]
@x70b1 `for_window [class="Yad"] floating enable` :)

**Comment by mjturt** [comment]
Bspwm. Yes I totally forget to mention in the README that with tiling window managers Yad needs to be set floating. I'm adding that too.

**Comment by x70b1** [comment]
I work on the files. I will add an info.

**Comment by mjturt** [comment]
Actually yes for pos_y it can be better if it does not depend on mouse position at all.

**Comment by x70b1** [comment]
I merge that. We can fix that later.

**Pull request merged**
