### PR TITLE
Added polynews module

### PR DESCRIPTION
**Pull request by zemmsoares**
Polynews module - Module that shows the latest news into the polybar
Currently displays latest news from "The Guardians" into polybar using their API
As soon as I have some free time I will gather information on which news websites polybar users would like to see on the polynews module ,developing a script for each, since all websites have a different structure and some may require scraping!

### CODE REVIEW

**Comment by x70b1** [comment]
We can move it to `polybar-scripts` or you can maintain it in you own repository and we add a link here: [x70b1/polybar-scripts#see-also-these-other-user-repositories](https://github.com/x70b1/polybar-scripts#see-also-these-other-user-repositories)

What is the best? :wink:

**Comment by zemmsoares** [comment]
Link may be better since i will be adding more scripts once i got some time!
Thanks!

**Comment by zemmsoares** [comment]
@x70b1 Let me know once you can add a link to my repository!
Best regards!

**Comment by x70b1** [comment]
@zemmsoares Sorry for the delay dude!

**Pull request closed without merging**
